site_name: Template pour la documentation d'un composant geOrchestra

INHERIT: ./mkdocs_generic.yml

docs_dir: ../docs/fr
edit_uri: edit/main/docs/

theme:
  language: fr


extra:
  alternate:
    - name: Français
      link: /fr/
      lang: fr
    - name: English
      link: /en/
      lang: en

nav:
    - Accueil: index.md
    - Guide utilisateur:
        - Sommaire: guide_utilisateur/index.md
        - Prendre en main: guide_utilisateur/00_prise_en_main.md
        - Vue globale: guide_utilisateur/01_vue_globale.md
        - Barres ou menus d''outils: guide_utilisateur/02_outils.md
        - Aide syntaxe: guide_utilisateur/aide_syntaxe.md
    - Guides techniques:
        - Sommaire: guides_techniques/index.md
        - Administrer:
            - guides_techniques/administrer/index.md
            - guides_techniques/administrer/une_page.md
        - Installer:
            - guides_techniques/installer/index.md
            - guides_techniques/installer/00_presentation.md
            - guides_techniques/installer/01_prerequis.md
            - guides_techniques/installer/02_preparation.md
            - guides_techniques/installer/03_installation.md
            - guides_techniques/installer/04_configuration.md
            - guides_techniques/installer/05_debug.md
            - guides_techniques/installer/06_tests.md
        - Développer:
            - guides_techniques/developper/index.md
            - guides_techniques/developper/matrice_fonctionnalites.md
            - guides_techniques/developper/api.md



plugins:
    - toc-md:
        toc_page_title: Contents
        toc_page_description: Sommaire de la section
        header_level: 3
        pickup_description_meta: false
        pickup_description_class: false
        output_path: tableofcontent.md
        output_log: true
        ignore_page_pattern: index.md
        remove_navigation_page_pattern: index.md
        template_dir_path: custom_template
    - git-revision-date-localized:
        enable_creation_date: true


# TODO Documenter comment simplifier l'arborescence pour un petit projet
